[workspace]
members = ["crates/api", "crates/worker"]
resolver = "2"

[workspace.dependencies]
serde = "1.0.197"
tokio = { version = "1.36.0", features = ["full"] }

[package]
name = "demo-root"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
serde = { workspace = true }
serde-json = "1.0.108"

[dev-dependencies]
criterion = "0.5.1"
