import type {
  Diagnostic,
  RepairAction,
  RepairActionType,
  RepairPlan,
  RiskLevel,
} from '../core/models.js';
import { CreateFileTool } from '../repair/tools/create-file.js';
import { ModifyFileTool } from '../repair/tools/modify-file.js';
import { InstallDependencyTool } from '../repair/tools/install-dependency.js';
import { CreatePythonVenvTool } from '../repair/tools/create-python-venv.js';
import { diagnosticKey } from './analysis.js';
import type { AgentAnalysis } from './analysis.js';

export const MISSING_REQUIRED_FILE_CODE = 'MISSING_REQUIRED_FILE';
export const MISSING_PYTHON_VENV_CODE = 'MISSING_PYTHON_VENV';
export const CONFIG_VALUE_MISMATCH_CODE = 'CONFIG_VALUE_MISMATCH';

const ECOSYSTEM_TO_PACKAGE_MANAGER: Readonly<Record<string, 'npm' | 'pip' | 'cargo' | 'go' | 'composer' | 'bundler'>> = {
  node: 'npm',
  python: 'pip',
  rust: 'cargo',
  go: 'go',
  php: 'composer',
  ruby: 'bundler',
};

export interface PlannedManualAction {
  readonly description: string;
  readonly reason: string;
  readonly riskLevel: RiskLevel;
  readonly diagnosticKeys: ReadonlyArray<string>;
}

export interface PlanningInput {
  readonly analysis: AgentAnalysis;
  readonly workspaceRoot: string;
  readonly attemptedFingerprints?: ReadonlySet<string>;
}

export interface DeterministicPlan {
  readonly plan: RepairPlan;
  readonly manualActions: ReadonlyArray<PlannedManualAction>;
  readonly skippedFingerprints: ReadonlyArray<string>;
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value) ?? 'null';
  }
  if (Array.isArray(value)) {
    return `[${value.map((entry) => stableStringify(entry)).join(',')}]`;
  }
  const record = value as Readonly<Record<string, unknown>>;
  const keys = Object.keys(record).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`).join(',')}}`;
}

export function actionFingerprint(action: Pick<RepairAction, 'type' | 'target' | 'parameters'>): string {
  const parameters = { ...(action.parameters as Record<string, unknown>) };
  delete parameters['workspaceRoot'];
  return stableStringify({ type: action.type, target: action.target, parameters });
}

function candidatePayload(diagnostic: Diagnostic): Readonly<Record<string, unknown>> {
  const candidate = diagnostic.remediationCandidates?.[0];
  return candidate?.payload ?? {};
}

function buildAction(
  id: string,
  type: RepairActionType,
  description: string,
  diagnostic: Diagnostic,
  parameters: Readonly<Record<string, unknown>>,
  workspaceRoot: string
): RepairAction {
  return {
    id,
    type,
    permissionLevel: 'project-modification',
    description,
    target: { filePath: diagnostic.affectedFiles?.[0] },
    parameters: { ...parameters, workspaceRoot },
    affectedFiles: diagnostic.affectedFiles ? [...diagnostic.affectedFiles] : [],
    reversible: true,
    riskLevel: 'project-modification',
    prerequisites: [],
  };
}

function manualFor(diagnostic: Diagnostic, reason: string, riskLevel: RiskLevel): PlannedManualAction {
  return {
    description: `Manual action required: ${diagnostic.title}`,
    reason,
    riskLevel,
    diagnosticKeys: [diagnosticKey(diagnostic)],
  };
}

export class DeterministicRepairPlanner {
  createPlan(input: PlanningInput): Promise<DeterministicPlan> {
    const actions: RepairAction[] = [];
    const manualActions: PlannedManualAction[] = [];
    const skippedFingerprints: string[] = [];
    const seen = new Set<string>();

    const consider = (action: RepairAction): void => {
      const fingerprint = actionFingerprint(action);
      if (seen.has(fingerprint)) {
        return;
      }
      seen.add(fingerprint);
      if (input.attemptedFingerprints?.has(fingerprint)) {
        skippedFingerprints.push(fingerprint);
        return;
      }
      actions.push(action);
    };

    for (const diagnostic of input.analysis.blockingDiagnostics) {
      const candidates = this.mapDiagnosticToActions(diagnostic, input.workspaceRoot);
      for (const action of candidates.executable) {
        consider(action);
      }
      for (const manual of candidates.manual) {
        manualActions.push(manual);
      }
    }

    const plan: RepairPlan = {
      id: `plan-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
      name: `Deterministic repair plan for ${input.analysis.blockingDiagnostics.length} blocking diagnostics`,
      description: 'Generated by the deterministic repair planner without AI',
      actions,
      estimatedDuration: actions.length * 5000,
      requiresApproval: actions.some((action) => action.permissionLevel !== 'read-only'),
    };

    return Promise.resolve({ plan, manualActions, skippedFingerprints });
  }

  private mapDiagnosticToActions(
    diagnostic: Diagnostic,
    workspaceRoot: string
  ): { readonly executable: ReadonlyArray<RepairAction>; readonly manual: ReadonlyArray<PlannedManualAction> } {
    const id = (suffix: string): string =>
      `action-${Date.now()}-${suffix}-${Math.random().toString(36).slice(2, 7)}`;

    if (diagnostic.code === MISSING_REQUIRED_FILE_CODE) {
      const payload = candidatePayload(diagnostic);
      const action = buildAction(
        id('file'),
        'create-environment',
        `Create required file ${String(payload['path'] ?? diagnostic.affectedFiles?.[0] ?? 'unknown')}`,
        diagnostic,
        { path: payload['path'], content: payload['content'] },
        workspaceRoot
      );
      if (new CreateFileTool().validate(action).valid) {
        return { executable: [action], manual: [] };
      }
      return {
        executable: [],
        manual: [manualFor(diagnostic, 'Required file payload is incomplete or unsafe', 'project-modification')],
      };
    }

    if (diagnostic.code === MISSING_PYTHON_VENV_CODE) {
      const payload = candidatePayload(diagnostic);
      const parameters: Record<string, unknown> = { path: payload['path'] };
      if (payload['pythonExecutable'] !== undefined) {
        parameters['pythonExecutable'] = payload['pythonExecutable'];
      }
      const action = buildAction(
        id('venv'),
        'create-environment',
        `Create Python virtual environment ${String(payload['path'] ?? 'unknown')}`,
        diagnostic,
        parameters,
        workspaceRoot
      );
      if (new CreatePythonVenvTool().validate(action).valid) {
        return { executable: [action], manual: [] };
      }
      return {
        executable: [],
        manual: [manualFor(diagnostic, 'Virtual environment payload is incomplete or unsafe', 'project-modification')],
      };
    }

    if (diagnostic.code === CONFIG_VALUE_MISMATCH_CODE) {
      const payload = candidatePayload(diagnostic);
      const action = buildAction(
        id('modify'),
        'modify-configuration',
        `Update configuration value in ${String(payload['path'] ?? diagnostic.affectedFiles?.[0] ?? 'unknown')}`,
        diagnostic,
        { path: payload['path'], find: payload['find'], replace: payload['replace'] },
        workspaceRoot
      );
      if (new ModifyFileTool().validate(action).valid) {
        return { executable: [action], manual: [] };
      }
      return {
        executable: [],
        manual: [manualFor(diagnostic, 'Configuration update payload is incomplete or unsafe', 'project-modification')],
      };
    }

    if (diagnostic.category === 'dependency' && diagnostic.requirement?.type === 'package-dependency') {
      const requirement = diagnostic.requirement;
      const ecosystem = ECOSYSTEM_TO_PACKAGE_MANAGER[requirement.ecosystem];
      if (!ecosystem) {
        return {
          executable: [],
          manual: [
            manualFor(
              diagnostic,
              `No controlled installer for ecosystem ${requirement.ecosystem}`,
              'project-modification'
            ),
          ],
        };
      }
      const parameters: Record<string, unknown> = {
        ecosystem,
        package: requirement.name,
      };
      if (requirement.versionConstraint) {
        parameters['version'] = requirement.versionConstraint;
      }
      const action = buildAction(
        id('dep'),
        'install-dependency',
        `Install ${requirement.name}${requirement.versionConstraint ? ` ${requirement.versionConstraint}` : ''}`,
        diagnostic,
        parameters,
        workspaceRoot
      );
      if (new InstallDependencyTool().validate(action).valid) {
        return { executable: [action], manual: [] };
      }
      return {
        executable: [],
        manual: [
          manualFor(
            diagnostic,
            `Package ${requirement.name} failed controlled-installer validation`,
            'project-modification'
          ),
        ],
      };
    }

    if (diagnostic.category === 'runtime' || diagnostic.category === 'toolchain' ||
        diagnostic.category === 'build' || diagnostic.category === 'container') {
      return {
        executable: [],
        manual: [
          manualFor(
            diagnostic,
            `No controlled repair tool for ${diagnostic.category} diagnostics; system-level change requires explicit manual action`,
            'system-modification'
          ),
        ],
      };
    }

    return {
      executable: [],
      manual: [manualFor(diagnostic, 'No known automated repair for this diagnostic', 'project-modification')],
    };
  }
}

export function createDeterministicRepairPlanner(): DeterministicRepairPlanner {
  return new DeterministicRepairPlanner();
}
