export {
  Project,
  Workspace,
  Environment,
  Diagnostic,
  RepairAction,
  RepairPlan,
  VerificationResult,
  AgentState,
  AgentEvidence,
  DiagnosisResult,
  PlanContext,
  Language,
  Ecosystem,
  Tool,
  Requirement,
  Dependency,
  RiskLevel,
  ProjectType,
  ManifestFormat,
  DependencySource,
  DependencyScope,
  EnvironmentType,
  RequirementType,
  DiagnosticSeverity,
  DiagnosticSource,
  RepairActionType,
  ToolCapability,
  AgentLifecycleStage,
} from './core/models.js';

export {
  WorkspaceManager,
  LanguageAnalyzer,
  EnvironmentAdapter,
  DiagnosticEngine,
  RepairTool,
  VerificationEngine,
  AIProvider,
  Agent,
  PermissionManager,
  AuditLogger,
  ToolRegistry,
  ProjectAnalysis,
  RuntimeInfo,
  CommandResult,
  RepairContext,
  RepairExecutionResult,
  RollbackResult,
  VerificationContext,
  VerificationRule,
  ApprovalResult,
  PermissionPolicy,
  PermissionDecision,
  AuditEvent,
  AuditActor,
  AuditTarget,
  AuditQuery,
  AuditEventType,
  PlanConstraints,
  RootCause,
  EnvironmentSnapshot,
} from './core/interfaces.js';

export { NoAIProvider, AIProviderConfig, LocalAIConfig, ExternalAIConfig, createAIProvider, AIProviderType } from './ai/providers.js';

export { DEFAULT_PERMISSION_POLICY, getActionRiskLevel, checkPermission, PermissionManagerImpl } from './safety/permission.js';

export { AGENT_LIFECYCLE_STAGES, LIFECYCLE_TRANSITIONS, canTransition, createInitialAgentState, updateAgentState, transitionAgentState, AgentEngine, SimpleAgentEngine } from './agent/lifecycle.js';